// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShoppingCart.DAL.Data.Context;

#nullable disable

namespace ShoppingCart.DAL.Migrations
{
    [DbContext(typeof(ProductContext))]
    [Migration("20240428200105_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShoppingCart.DAL.Data.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("cartItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductId = 1,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 2,
                            ProductId = 2,
                            Quantity = 3
                        },
                        new
                        {
                            Id = 3,
                            ProductId = 2,
                            Quantity = 4
                        },
                        new
                        {
                            Id = 4,
                            ProductId = 4,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 5,
                            ProductId = 3,
                            Quantity = 4
                        });
                });

            modelBuilder.Entity("ShoppingCart.DAL.Data.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDateTime = new DateTime(2024, 4, 28, 23, 1, 5, 163, DateTimeKind.Local).AddTicks(2178),
                            TotalPrice = 1000m
                        },
                        new
                        {
                            Id = 2,
                            CreationDateTime = new DateTime(2024, 4, 28, 23, 1, 5, 163, DateTimeKind.Local).AddTicks(2244),
                            TotalPrice = 2000m
                        },
                        new
                        {
                            Id = 3,
                            CreationDateTime = new DateTime(2024, 4, 28, 23, 1, 5, 163, DateTimeKind.Local).AddTicks(2247),
                            TotalPrice = 3000m
                        },
                        new
                        {
                            Id = 4,
                            CreationDateTime = new DateTime(2024, 4, 28, 23, 1, 5, 163, DateTimeKind.Local).AddTicks(2250),
                            TotalPrice = 4000m
                        },
                        new
                        {
                            Id = 5,
                            CreationDateTime = new DateTime(2024, 4, 28, 23, 1, 5, 163, DateTimeKind.Local).AddTicks(2252),
                            TotalPrice = 5000m
                        });
                });

            modelBuilder.Entity("ShoppingCart.DAL.Data.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "computers",
                            Name = "product1",
                            Price = 2000m,
                            Quantity = 10
                        },
                        new
                        {
                            Id = 2,
                            Category = "TV",
                            Name = "product2",
                            Price = 4000m,
                            Quantity = 20
                        },
                        new
                        {
                            Id = 3,
                            Category = "Watches",
                            Name = "product3",
                            Price = 2000m,
                            Quantity = 10
                        },
                        new
                        {
                            Id = 4,
                            Category = "Smart Watches",
                            Name = "product4",
                            Price = 2890m,
                            Quantity = 50
                        },
                        new
                        {
                            Id = 5,
                            Category = "Laptops",
                            Name = "product5",
                            Price = 2900m,
                            Quantity = 90
                        });
                });

            modelBuilder.Entity("ShoppingCart.DAL.Data.Models.CartItem", b =>
                {
                    b.HasOne("ShoppingCart.DAL.Data.Models.Order", null)
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId");

                    b.HasOne("ShoppingCart.DAL.Data.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ShoppingCart.DAL.Data.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
